# Generated by Django 3.0.3 on 2020-02-23 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('localApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='localApp.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='localApp.Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 16, 50, 16, 82644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 16, 50, 16, 81930, tzinfo=utc)),
        ),
    ]
