# Generated by Django 3.0.3 on 2020-02-25 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('localApp', '0002_auto_20200223_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 12, 7, 40, 725425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 12, 7, 40, 724708, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Post_Likes_Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='localApp.Posts')),
            ],
        ),
    ]
