# Generated by Django 3.0.3 on 2020-02-26 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 19, 5, 26, 71577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 19, 5, 26, 70890, tzinfo=utc)),
        ),
    ]
