# Generated by Django 3.0.3 on 2020-02-27 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_auto_20200227_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='djangoApp.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 20, 47, 52, 593572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 20, 47, 52, 592880, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
