# Generated by Django 3.0.3 on 2020-02-26 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_auto_20200226_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 20, 55, 58, 902814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 20, 55, 58, 901815, tzinfo=utc)),
        ),
    ]
