# Generated by Django 3.0.3 on 2020-02-28 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoApp', '0004_auto_20200228_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='userId',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 11, 8, 33, 155176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 11, 8, 33, 153874, tzinfo=utc)),
        ),
    ]
