# Generated by Django 3.0.3 on 2020-02-28 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_auto_20200228_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forbidden_Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 12, 37, 38, 970905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 12, 37, 38, 969615, tzinfo=utc)),
        ),
    ]
